### PR TITLE
Added several new DST ingredients and recipes

### PR DESCRIPTION
**Pull request by 6lancmange**
(Potato, Garlic, Toma Root, Onion, and their cooked versions)

Sorry, I don't get why it shows that Pepper etc. from previous time is also shown as changed. I'm not very knowledgeable about how all this works. Should I create an extra branch and commit to it instead, and then open a pull request from that one? It did say it could automatically merge last time, and now it's not possible. Is that okay?

### CODE REVIEW

**Comment by lakhnishMonster** [comment]
How did you add the images for the foods? I wish to do the same for my fork. Thanks!

**Comment by 6lancmange** [comment]
They're in the img folder, haha

**Comment by 6lancmange** [comment]
Yep, I corrected those now. I added the Mandrake restriction because the wiki lists it, but I don't think it's necessary, it's only forbidden because it will result in Mandrake Soup, caused by its high priority. Bacon and Eggs also supposedly requires 2 eggs, but that's indeed not true, it requires more than one. So if they add something with the egg value of 0.5, it should be possible to make the meal with 1.5 eggs.

Whoops, I noticed now that I checked all recipes up to Powdercake, but didn't actually correct the Butter Muffin, gonna add another commit in a minute.

**Comment by 6lancmange** [comment]
Since the original post doesn't reflect all the changes, here's a summary of what I did:
- ingredients: (Roasted) Potato, (Roasted) Garlic, (Roasted) Toma Root, (Roasted) Onion, (Roasted) Juicy Berries and Moon Moth Wings, (Cooked, Dried) Kelp Fronds, Lune Tree Blossom, (Ripe and Cooked) Stone Fruit
- recipes: Creamy Potato Purée, Salsa Fresca, Fancy Spiralled Tubers
- updated Butter Muffin to accept Moon Moth Wings, Waffles and Trail Mix to accept Juicy Berries, Guacamole to accept Ripe Stone Fruit
- added dry_superfast taking a quarter of a day, only used in Kelp as of now

**Comment by lakhnishMonster** [comment]
"updated Butter Muffin to accept Moon Moth Wings, Waffles and Trail Mix to accept Juicy Berries, Guacamole to accept Ripe Stone Fruit"

I thought this was an issue b/c there are differences across versions (issue #32). I'm not sure putting an OR case for this was the correct solution?

I was also looking at the recipes for potatotornado & mashedpotatoes in the pull thread, and I'm not sure they are correct either (no mention of twigs and odd potato math respectively)?

Guess I'll make corrections tomorrow?

**Comment by 6lancmange** [comment]
Oh crap, you're right. It only makes sense in DST. But that will accept the other ingredients that are acceptable apart from the regular ones. To separate the DST-exclusive recipes, some bigger rework is needed.

Why is the math odd? This was the only way I managed to make it accept cooked or raw and not necessarily both being the same state. Although I admit, I don't know how elegant of a solution it is.

As far as I know, Twigs seem to be the only inedible ingredient so I didn't specifically write them, but I was going to correct all the recipes according to the game file later, and I see now that they are listed.

**Comment by lakhnishMonster** [comment]
For the potato math, I meant more so with just following the logic listed as by Klei (which you said somewhere as well elsewhere). 

As for inedibles; Nightmare Fuel, Volt Goat Horns, and Bone Shards are new inedible ingredients for the crockpot (cooking Dragonpies with Dragon Fruit + 3 Nightmare Fuel is the new meta /s; i.e. it works). 

I just copied the logic as listed by Klei again for the potatotornado recipe, which said twigs are a requirement and would also be needed due to their being more inedibles in the game as mentioned.

**Pull request merged**
