### PR TITLE
A (Mostly) Complete Fix to the Crockpot Simulator

### PR DESCRIPTION
**Pull request by lakhnishMonster**
The following was done to (almost) completely fix the crockpot simulator and keep it up-to-date with DS and DST as of August 5, 2023.

@bluehexagons  A live version of the simulator can be viewed here to verify that the simulator is working:
https://lakhnishmonster.github.io/foodguide/html/index.htm

The large commit number is due to messing around with what worked in the simulator and what broke due to user errors or tertiary reasons.

### Major Changes to Bits & Masks:
- The Don't Starve Together mask no longer uses VANILLA or GIANTS masks and instead only uses the TOGETHER mask. 

**Note:** This meant that the overlapping ingredients and recipes from Don't Starve + DLCs had to be ported over to DST by being listed twice. The solution to any problems this would cause was to give such ingredients and recipes the '_dst' suffix for the following reasons:

1.  ID purposes to limit coding errors (ex. changed bananapop recipe in DS when you meant to do that for DST)
2. Was needed to make the simulator work when the prefabname of the ingredient existed across both DS and DST. For example, asparagus exists in Hamlet and DST, but the old mask system wouldn't work for that. 
3. Would account for differences in the data values of ingredients and recipes (ex. Glowberries can be cooked in the crockpot in DST but not DS).
4. Allowed the recipes across the two games to refer to the same image, saving a lot of work (for example, asparagussoup from hamlet and asparagussoup_dst would refer to the same image since they have the same display name of 'Asparagus Soup', even though they have differing recipes).

The trade-off is remembering to refer to such ported ingredients with '_dst' suffix, which is a small price to pay for fixing the simulator (and the simulator would break when I tried giving dst exclusive ingredients the '_dst' suffix for reasons I don't know). A note is listed in the relevant sections in the code as a reminder.

- Added a new bit and mask for Warly in Hamlet and DST (WARLYHAM mask uses DS + all three DLC masks; WARLYDST mask uses only the TOGETHER and WARLYDST mask.)
- Added big comment dividers to improve legibility of what recipes and ingredients belong to which game/DLC as well as notes for future individuals who want to make changes to the simulator.

### Don't Starve Changes:
- Feijoida's recipe was fixed in the latest DS QoL update so that you can't do bean bug shenanigans to skip the meat requirement. A note is left in case a user is playing on the pre2023update branch of DS.
- Ice Cream is a veggie, not a goodie in DS + DLCs.
- Added the Winter Koalefant Trunk.
- Cooked Eel was missing it's fish and meat value.
- Fixed the cooked version of mushrooms not showing up next to their raw versions.

### DST Changes:
- Overlapping recipes and ingredients from DS + DLCs were ported over to DST, accounting for differences in both ingredient values and recipe formulas. 

**NOTE:** These recipes and ingredients have a '_dst' suffix at the end for the reasons previously listed. **Future changes need to take this account when listing ingredients under DST recipes.**

Unfortunately, said suffix could not be added to all DST exclusive ingredients for consistency, as the simulator would stop working for reasons I do not understand. In exchange, this simulator gets to be up-to-date. More info is commented in the code at the relevant locations.
- Added the small ocean fish numbers 6-to-9 and medium ocean fish numbers 6-to-9 to DST. Also removed the rot and cook aspects to these ingredients, since it seemed to break the simulator when inputting what they actually rot or cook into (it had incorrect information before).
- Added missing DST exclusive recipes (ie Vegetable Stinger, Amberosia, and the refined dust ingredient).
- Added all of Warly's recipes under the warlydst mask.
- Figs, Cooked Figs and Barnacles were listed in DS when it's a DST exclusive ingredient.
- Fixed a typo where the spoilage timer of some recipes were listed as NEVER due to using perishtime instead of perish.
- Wobsters, Lobster Bisque and Lobster Dinner were added to DST but they had a naming conflict with their DS SW counterpart. They are referred to as wobster instead of lobster in the code when referring to their recipes in DST. Also added the word DST to their image and display names to resolve the conflict of having same image name as SW yet differing images in DST.
- Added Milky Whites as an ingredient.
- Added Live Eel as in ingredient and adjusted Unagi recipe accordingly.
- Ported the Winter Koalefant Trunk to DST and adjusted the Fig Stuffed Trunk recipe accordingly.

### Resolved Issues:
The changes made resolves the following issues:
#56 
#55 
#54 
#52 
#50 
#48 
#47 
#46 
#32 
#26 
#21 (this was actually fixed before any changes I made, not sure what to do about this user's other suggestion though)

This also means pull request #57 and #49 should be closed to prevent this work from being undone.

### CODE REVIEW

**Comment by bluehexagons** [comment]
Holy moly. I'll check this out as soon as possible, hopefully this weekend. Thank you!

**Review by bluehexagons — COMMENTED** [review]
Looks good to me. I'll test some more and merge tomorrow if (or when) you think you're done making changes. Thank you for getting this project up to a decent standard again!

**Comment by lakhnishMonster** [comment]
> Looks good to me. I'll test some more and merge tomorrow if (or when) you think you're done making changes. Thank you for getting this project up to a decent standard again!

No problem!

The only thing left that I've noticed is that the ingredients are not being listed next to each other in the DST mask when they should be (for example, Banana and Cooked Banana are not next to each other). I think it's a side effect of porting the ingredients to DST.

Once I've got stuffed grouped together again (probably tomorrow), I think we should be good!

**Comment by lakhnishMonster** [comment]
@bluehexagons I am done on my end now!

**Comment by lakhnishMonster** [comment]
@bluehexagons I've noticed that the .com (aka live version) is still using the old simulator!

**Comment by bluehexagons** [comment]
> @bluehexagons I've noticed that the .com (aka live version) is still using the old simulator!

Yep! I was working on some quick changes and took a shot at fixing #59 before redeploying the site. I appreciate the reminder.

**Pull request merged**
